package com.mycompany.telas;

import java.io.IOException;
import java.time.LocalDateTime;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import com.mycompany.tabelas.Maquina;
import com.mycompany.tabelas.Localizacao;
import com.mycompany.tabelas.Registro;
import com.mycompany.conexaoservidor.ClienteApi;
import com.mycompany.Converssao;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Gabriel Vieira
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TesteImagen
     */
    boolean monitorando = false;
        ClienteApi cliente = new ClienteApi();
        Localizacao localizacao = cliente.getLocalizacacao(1);
        Maquina maquina = new Maquina(localizacao);
    public TelaPrincipal() throws IOException {
        initComponents();
        
//        if(cliente.getMaquina(maquina.getSerial_number()) == null){
//            try {
//                cliente.criarMaquina(maquina);
//            } catch (IOException ex) {
//                Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        }else{
//            Maquina atualizada = cliente.getMaquina(maquina.getSerial_number());
//            cliente.atualizarMaquina(atualizada.getId_maquina(),atualizada);
//        }
        
        Thread threadDataHora = new Thread(this::atualizarHora);
        threadDataHora.start();
        
        lblFabricante.setText(maquina.getFabricante());
        lblModelo.setText(maquina.getModelo());
        lblSistemaOp.setText(maquina.getSistema_operacional());
        lblCPU.setText(maquina.getTipo_processador());
        lblTotalMemoriaRam.setText(String.format("%.2f GB", maquina.getRam_total()));
        lblLinha.setText(localizacao.getTipo_linha());
        lblEstacao.setText(localizacao.getNome_localizacao());
        lblHD.setText(String.format("%.2f GB", maquina.getCapacidade_memoria()));

        pgbUsoMemoria.setMaximum(100);
        pgbUsoMemoria.setMinimum(0);

        pgbUsoCPU.setMaximum(100);
        pgbUsoCPU.setMinimum(0);

        pgbUsoHD.setMaximum(100);
        pgbUsoHD.setMinimum(0);

        pgbUsoRAM.setMaximum(100);
        pgbUsoRAM.setMinimum(0);

        pgbTempCpu.setMaximum(100);
        pgbTempCpu.setMinimum(0);

        lblAvisoCapturar.setVisible(false);
        lblReticencias1.setVisible(false);
        lblReticencias2.setVisible(false);
        lblReticencias3.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        pgbUsoMemoria = new javax.swing.JProgressBar();
        pgbTempCpu = new javax.swing.JProgressBar();
        pgbUsoCPU = new javax.swing.JProgressBar();
        btnFechar = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        spnAtualizacao = new javax.swing.JSpinner();
        jLabel21 = new javax.swing.JLabel();
        btnParar1 = new javax.swing.JButton();
        btnParar = new javax.swing.JButton();
        btnProcessos = new javax.swing.JButton();
        btnAdministracao = new javax.swing.JButton();
        btnGraficos = new javax.swing.JButton();
        lblFabricante = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        lblUsuarioComputador = new javax.swing.JLabel();
        lblSistemaOp = new javax.swing.JLabel();
        pgbUsoHD = new javax.swing.JProgressBar();
        lblTempCPU = new javax.swing.JLabel();
        lblUsoProcessador = new javax.swing.JLabel();
        lblUsoMemoria = new javax.swing.JLabel();
        lblUsoDisco = new javax.swing.JLabel();
        lblCPU = new javax.swing.JLabel();
        lblTotalMemoriaRam = new javax.swing.JLabel();
        lblHD = new javax.swing.JLabel();
        lblLinha = new javax.swing.JLabel();
        lblEstacao = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        pgbUsoRAM = new javax.swing.JProgressBar();
        lblUsoRAM = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        btnMonitorar = new javax.swing.JButton();
        lblAvisoCapturar = new javax.swing.JLabel();
        lblReticencias2 = new javax.swing.JLabel();
        lblReticencias1 = new javax.swing.JLabel();
        lblReticencias3 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(111, 44, 145));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alpe_logo_editado.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Memoria Ram Total:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Sistema");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fabricante:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Modelo:");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Usuario:");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Sistema Op:");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CPU:");

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Uso de Memoria");

        jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Total de memória:");

        jLabel15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Uso do Disco");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Monitoramento");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Uso da CPU");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Temperatura da CPU");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/linha_lilas.png"))); // NOI18N

        jLabel17.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Usuario:");

        jLabel18.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Linha:");

        jLabel19.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Estação:");

        btnFechar.setBackground(new java.awt.Color(111, 44, 145));
        btnFechar.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btnFechar.setForeground(new java.awt.Color(255, 255, 255));
        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/x_editado.png"))); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.setBorder(null);
        btnFechar.setBorderPainted(false);
        btnFechar.setContentAreaFilled(false);
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Tempo de atualização:");

        spnAtualizacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spnAtualizacaoMouseClicked(evt);
            }
        });
        spnAtualizacao.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                spnAtualizacaoInputMethodTextChanged(evt);
            }
        });
        spnAtualizacao.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                spnAtualizacaoPropertyChange(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("segundos");

        btnParar1.setBackground(new java.awt.Color(39, 189, 190));
        btnParar1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnParar1.setForeground(new java.awt.Color(255, 255, 255));
        btnParar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnParar.png"))); // NOI18N
        btnParar1.setBorder(null);
        btnParar1.setBorderPainted(false);
        btnParar1.setContentAreaFilled(false);
        btnParar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParar1ActionPerformed(evt);
            }
        });

        btnParar.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnParar.setForeground(new java.awt.Color(255, 255, 255));
        btnParar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnSair.png"))); // NOI18N
        btnParar.setText("Sair");
        btnParar.setToolTipText("");
        btnParar.setBorder(null);
        btnParar.setBorderPainted(false);
        btnParar.setContentAreaFilled(false);
        btnParar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPararActionPerformed(evt);
            }
        });

        btnProcessos.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnProcessos.setForeground(new java.awt.Color(255, 255, 255));
        btnProcessos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/planilha_editado.png"))); // NOI18N
        btnProcessos.setText("Processos");
        btnProcessos.setContentAreaFilled(false);

        btnAdministracao.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAdministracao.setForeground(new java.awt.Color(255, 255, 255));
        btnAdministracao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gerente_Editado.png"))); // NOI18N
        btnAdministracao.setText("Administração");
        btnAdministracao.setBorderPainted(false);
        btnAdministracao.setContentAreaFilled(false);

        btnGraficos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnGraficos.setForeground(new java.awt.Color(255, 255, 255));
        btnGraficos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafico_editado.png"))); // NOI18N
        btnGraficos.setText("Graficos");
        btnGraficos.setBorderPainted(false);
        btnGraficos.setContentAreaFilled(false);
        btnGraficos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblFabricante.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblFabricante.setForeground(new java.awt.Color(255, 255, 255));
        lblFabricante.setText("Fabricante");

        lblModelo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblModelo.setForeground(new java.awt.Color(255, 255, 255));
        lblModelo.setText("Modelo");

        lblUsuarioComputador.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblUsuarioComputador.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuarioComputador.setText("Usuario");

        lblSistemaOp.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblSistemaOp.setForeground(new java.awt.Color(255, 255, 255));
        lblSistemaOp.setText("S.O");

        lblTempCPU.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblTempCPU.setForeground(new java.awt.Color(255, 255, 255));
        lblTempCPU.setText("0%");

        lblUsoProcessador.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblUsoProcessador.setForeground(new java.awt.Color(255, 255, 255));
        lblUsoProcessador.setText("0%");

        lblUsoMemoria.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblUsoMemoria.setForeground(new java.awt.Color(255, 255, 255));
        lblUsoMemoria.setText("0%");

        lblUsoDisco.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblUsoDisco.setForeground(new java.awt.Color(255, 255, 255));
        lblUsoDisco.setText("0%");

        lblCPU.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblCPU.setForeground(new java.awt.Color(255, 255, 255));
        lblCPU.setText("CPU");

        lblTotalMemoriaRam.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblTotalMemoriaRam.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalMemoriaRam.setText("Total de Memoria Ram");

        lblHD.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblHD.setForeground(new java.awt.Color(255, 255, 255));
        lblHD.setText("Total de memória:");

        lblLinha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblLinha.setForeground(new java.awt.Color(255, 255, 255));
        lblLinha.setText("Linha");

        lblEstacao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblEstacao.setForeground(new java.awt.Color(255, 255, 255));
        lblEstacao.setText("Estação");

        lblUsuario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("Usuario");

        jLabel23.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Uso de RAM");

        lblUsoRAM.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblUsoRAM.setForeground(new java.awt.Color(255, 255, 255));
        lblUsoRAM.setText("0%");

        lblData.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblData.setForeground(new java.awt.Color(255, 255, 255));
        lblData.setText("DD/MM/AAAA");

        lblHora.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblHora.setForeground(new java.awt.Color(255, 255, 255));
        lblHora.setText("HH:MM");

        btnMonitorar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnMonitorar.png"))); // NOI18N
        btnMonitorar.setBorderPainted(false);
        btnMonitorar.setContentAreaFilled(false);
        btnMonitorar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMonitorarActionPerformed(evt);
            }
        });

        lblAvisoCapturar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblAvisoCapturar.setForeground(new java.awt.Color(255, 255, 255));
        lblAvisoCapturar.setText("Capturando informações");

        lblReticencias2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblReticencias2.setForeground(new java.awt.Color(255, 255, 255));
        lblReticencias2.setText(".");

        lblReticencias1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblReticencias1.setForeground(new java.awt.Color(255, 255, 255));
        lblReticencias1.setText(".");

        lblReticencias3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblReticencias3.setForeground(new java.awt.Color(255, 255, 255));
        lblReticencias3.setText(".");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblAvisoCapturar)
                                        .addGap(8, 8, 8)
                                        .addComponent(lblReticencias1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(7, 7, 7)
                                        .addComponent(lblReticencias2, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblReticencias3, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel20))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jLabel9))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(spnAtualizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel21)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnMonitorar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnParar1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))))))
                        .addGap(108, 108, 108))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(58, 58, 58)
                                        .addComponent(jLabel18)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblLinha))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblUsuario)
                                        .addGap(50, 50, 50)
                                        .addComponent(btnParar)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblData)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(78, 78, 78)
                                        .addComponent(jLabel19)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblEstacao)
                                        .addGap(148, 148, 148))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addComponent(lblHora)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnFechar))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblUsuarioComputador)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblSistemaOp)
                                            .addComponent(lblCPU)
                                            .addComponent(lblModelo)
                                            .addComponent(lblFabricante)
                                            .addComponent(lblTotalMemoriaRam)
                                            .addComponent(lblHD)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 30, Short.MAX_VALUE)
                                                .addComponent(btnGraficos, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(55, 55, 55)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(btnAdministracao)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel11)
                                                    .addComponent(jLabel15)
                                                    .addComponent(jLabel23)
                                                    .addComponent(jLabel13)
                                                    .addComponent(jLabel10))
                                                .addGap(30, 30, 30)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(pgbTempCpu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblTempCPU))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(pgbUsoMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblUsoMemoria))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(pgbUsoCPU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblUsoProcessador))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(pgbUsoRAM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(pgbUsoHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(lblUsoRAM))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(164, 164, 164)
                                                .addComponent(lblUsoDisco))
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(27, 27, 27))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(btnProcessos)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(lblUsuario))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnParar, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblData)
                        .addComponent(lblHora)
                        .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(lblLinha)
                    .addComponent(lblEstacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnParar1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(spnAtualizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21)
                        .addComponent(btnMonitorar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAvisoCapturar)
                            .addComponent(lblReticencias2)
                            .addComponent(lblReticencias1)
                            .addComponent(lblReticencias3))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblFabricante))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblModelo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(lblCPU))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(lblHD))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(lblTotalMemoriaRam))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSistemaOp)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pgbTempCpu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(lblTempCPU))
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pgbUsoCPU, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblUsoProcessador, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(pgbUsoMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(pgbUsoHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lblUsoMemoria)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblUsoRAM)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(pgbUsoRAM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(11, 11, 11)
                                                .addComponent(lblUsoDisco))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel15)))))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(lblUsuarioComputador))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnProcessos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGraficos, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdministracao, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPararActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPararActionPerformed

    private void btnParar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParar1ActionPerformed
        monitorando = false;
    }//GEN-LAST:event_btnParar1ActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFecharActionPerformed

    private void spnAtualizacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spnAtualizacaoMouseClicked

    }//GEN-LAST:event_spnAtualizacaoMouseClicked

    private void spnAtualizacaoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_spnAtualizacaoPropertyChange
    }//GEN-LAST:event_spnAtualizacaoPropertyChange

    private void spnAtualizacaoInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_spnAtualizacaoInputMethodTextChanged

    }//GEN-LAST:event_spnAtualizacaoInputMethodTextChanged

    private void btnMonitorarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMonitorarActionPerformed
        Integer valor = Integer.valueOf(spnAtualizacao.getValue().toString());
        if (!monitorando) {
            if (valor < 3) {
                spnAtualizacao.setValue(3);
            } else {
                Thread threadMonitoramento = new Thread(this::atualizarDados);
                Thread threadReticencias = new Thread(this::reticencias);

                threadMonitoramento.start();
                threadReticencias.start();

                monitorando = true;
            }
        }
    }//GEN-LAST:event_btnMonitorarActionPerformed

    public void atualizarHora(){
        while (true){
        List<String> dataHora = Converssao.dataHoraFormatoBrasileiro(LocalDateTime.now().toString());
        lblData.setText(dataHora.get(0));
        lblHora.setText(dataHora.get(1));
        try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
            }
        }
        
    }
    
    public void atualizarDados() {
        Integer valor = Integer.valueOf(spnAtualizacao.getValue().toString());
        Integer tempo = valor * 1000;
        while (monitorando) {
        Registro registro = new Registro(maquina);
//Uso do Disco e uso da CPU estão errados

        lblUsoMemoria.setText(String.format("%.1f %%", registro.getPorc_memoria()));
        lblUsoProcessador.setText(String.format("%.1f%%", registro.getPorc_processador()));
        lblUsoRAM.setText(String.format("%.1f%%", registro.getPorc_ram()));
        lblTempCPU.setText(String.format("%.0fºC", registro.getTemp_cpu()));
        lblUsoDisco.setText(String.format("%.1f%%", registro.getPorc_disco()));
            
        pgbUsoMemoria.setValue(Integer.parseInt(String.format("%.0f", registro.getPorc_memoria())));
        pgbUsoCPU.setValue(Integer.parseInt(String.format("%.0f", registro.getPorc_processador())));
        pgbUsoHD.setValue(Integer.parseInt(String.format("%.0f", registro.getPorc_disco())));
        pgbUsoRAM.setValue(Integer.parseInt(String.format("%.0f", registro.getPorc_ram())));
        pgbTempCpu.setValue(Integer.parseInt(String.format("%.0f", registro.getTemp_cpu())));

            try {
                Thread.sleep(tempo);
            } catch (InterruptedException e) {
            }
        }
     
    }

    public void reticencias() {
        while (monitorando) {

            lblAvisoCapturar.setVisible(true);
            try {Thread.sleep(200);} catch (InterruptedException e) {}
            lblReticencias1.setVisible(true);
            try {Thread.sleep(200);} catch (InterruptedException e) {}
            lblReticencias2.setVisible(true);
            try {Thread.sleep(200);} catch (InterruptedException e) {}
            lblReticencias3.setVisible(true);
            try {Thread.sleep(200);} catch (InterruptedException e) {}
            
            lblReticencias1.setVisible(false);
            try {Thread.sleep(200);} catch (InterruptedException e) {}
            lblReticencias2.setVisible(false);
            try {Thread.sleep(200);} catch (InterruptedException e) {}
            lblReticencias3.setVisible(false);
            try {Thread.sleep(200);} catch (InterruptedException e) {}

        }
        lblAvisoCapturar.setVisible(false);
        lblReticencias1.setVisible(false);
        lblReticencias2.setVisible(false);
        lblReticencias3.setVisible(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TelaPrincipal().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdministracao;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnGraficos;
    private javax.swing.JButton btnMonitorar;
    private javax.swing.JButton btnParar;
    private javax.swing.JButton btnParar1;
    private javax.swing.JButton btnProcessos;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lblAvisoCapturar;
    private javax.swing.JLabel lblCPU;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblEstacao;
    private javax.swing.JLabel lblFabricante;
    private javax.swing.JLabel lblHD;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblLinha;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblReticencias1;
    private javax.swing.JLabel lblReticencias2;
    private javax.swing.JLabel lblReticencias3;
    private javax.swing.JLabel lblSistemaOp;
    private javax.swing.JLabel lblTempCPU;
    private javax.swing.JLabel lblTotalMemoriaRam;
    private javax.swing.JLabel lblUsoDisco;
    private javax.swing.JLabel lblUsoMemoria;
    private javax.swing.JLabel lblUsoProcessador;
    private javax.swing.JLabel lblUsoRAM;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblUsuarioComputador;
    private javax.swing.JProgressBar pgbTempCpu;
    private javax.swing.JProgressBar pgbUsoCPU;
    private javax.swing.JProgressBar pgbUsoHD;
    private javax.swing.JProgressBar pgbUsoMemoria;
    private javax.swing.JProgressBar pgbUsoRAM;
    private javax.swing.JSpinner spnAtualizacao;
    // End of variables declaration//GEN-END:variables
}
